### ISSUE TITLE
Add parameter to append to release body

### ISSUE THREAD

**Issue by Delwing** [rymndhng/release-on-push-action#38]
It would be really great to append own message to body (e.g. if I run `repository_dispatch` I can pass some payload that will end up in body).

e.g
```
      uses: rymndhng/release-on-push-action@master
      with:
        bump_version_scheme: minor
        body: ${{ github.event.client_payload.message }}
```
