### ISSUE TITLE
How to calculate version, change files and then release in the same workflow?

### ISSUE THREAD

**Issue by DasBen** [rymndhng/release-on-push-action#86]
I got a small problem. This action calculates the version while doing the release. Sadly I need the release version before so that I could edit some changelog files with that version number. So I tried:

```
      - name: Release-Version nur kalkulieren
        id: calculate_release_version
        uses: rymndhng/release-on-push-action@v0.27.0
        env:
          GITHUB_TOKEN: ${{ env.TOKEN }}
        with:
          tag_prefix: ""
          bump_version_scheme: norelease

      - name: Check Output Parameters bevor Release erstellt wird
        run: |
          echo "Got tag name ${{ steps.calculate_release_version.outputs.tag_name }}"
          echo "Got release version ${{ steps.calculate_release_version.outputs.version }}"
          echo "Upload release artifacts to ${{ steps.calculate_release_version.outputs.upload_url }}"

      - name: Set release version in db changes - Does not matter how
      
      - name: Release erstellen
        id: create_release
        uses: rymndhng/release-on-push-action@v0.27.0
        env:
          GITHUB_TOKEN: ${{ env.TOKEN }}
        with:
          tag_prefix: ""
          bump_version_scheme: patch
          use_github_release_notes: true
          release_body: "When set, adds extra text to body!"

      - name: Check Output Parameters nach Release Erstellung
        run: |
          echo "Got tag name ${{ steps.create_release.outputs.tag_name }}"
          echo "Got release version ${{ steps.create_release.outputs.version }}"
          echo "Upload release artifacts to ${{ steps.create_release.outputs.upload_url }}"
```

Sadly if the pull-request has any label with release:patch, release:minor, release:major set, then the "bump_version_scheme: norelease" gets overwritten as stated on the readme. Any idea on how to only calculate the version with this? I could do it with adding another action, but this one is so cool, that I do not really want to.

**Comment by DasBen** [comment]
I've just looked through the releases and found out that there is a "with: dry_run: true" which does the trick. 😁 Thanks for that I totally missed that one, because it is not on the readme.

```
      - name: Release Version nur berechnen
        id: calculate_release_version
        uses: rymndhng/release-on-push-action@v0.28.0
        env:
          GITHUB_TOKEN: ${{ env.TOKEN }}
        with:
          tag_prefix: ""
          bump_version_scheme: norelease
          dry_run: true

      - name: Check Output Parameters bevor Release erstellt wird
        run: |
          echo "Got tag name ${{ steps.calculate_release_version.outputs.tag_name }}"
          echo "Got release version ${{ steps.calculate_release_version.outputs.version }}"
          echo "Upload release artifacts to ${{ steps.calculate_release_version.outputs.upload_url }}"

      - name: Set release version in db changes - Does not matter how
      
      - name: Release erstellen
        id: create_release
        uses: rymndhng/release-on-push-action@v0.27.0
        env:
          GITHUB_TOKEN: ${{ env.TOKEN }}
        with:
          tag_prefix: ""
          bump_version_scheme: patch
          use_github_release_notes: true
          release_body: "When set, adds extra text to body!"

      - name: Check Output Parameters nach Release Erstellung
        run: |
          echo "Got tag name ${{ steps.create_release.outputs.tag_name }}"
          echo "Got release version ${{ steps.create_release.outputs.version }}"
          echo "Upload release artifacts to ${{ steps.create_release.outputs.upload_url }}"
```
