### ISSUE TITLE
Action bumps major version even though specified to create a release with patch bump.

### ISSUE THREAD

**Issue by anubhav-sl** [rymndhng/release-on-push-action#96]
When running the actions it was working fine previously but now it has been acting weird. It bumps major version creating releases like v2.0.0 , v3.0.0 and so on, even though I have specified to bump patch version. I also added `release:patch` label but that doesn't seem to work as well.

My Yml file
```
name: Development Release

on:
  workflow_dispatch:

jobs:
  release:
    name: 🚀 Tag development release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Tag development release
        uses: rymndhng/release-on-push-action@master
        with:
          max_commits: 100
          bump_version_scheme: patch
          tag_prefix: 'dev-release-v'
          use_github_release_notes: true

```

Logs:
```
{:input/release-name <RELEASE_TAG>, :github/api-url https://api.github.com,/ :github/output /github/file_commands/set_output_2fba5ef1-29ea-4dfe-a66c-e7b04a0aec26, :bump-version-scheme patch, :input/tag-prefix dev-release-v, :input/max-commits 100, :token ***, :input/release-body , :input/use-github-release-notes true, :repo brite-live/brite-apis, :dry-run false, :sha 23b9ca19...300fef9cad6b6a}
Fetching related data...
Generating release...
Executing Release
 {
  "tag_name" : "dev-release-v2.0.0",
  "target_commitish" : "23b9ca...f9cad6b6a",
  "name" : "dev-release-v2.0.0",
  "body" : "Version 2.0.0\n\n",
  "draft" : false,
  "prerelease" : false,
  "generate_release_notes" : true
}

```
